### ISSUE TITLE
Support KiCad 6

### ISSUE THREAD

**Issue by foostan** [foostan/kbd#7]

**Comment by sol** [comment]
@foostan I'm interested in contributing to the symbol library (e.g. setting default footprints for symbols, similar to what I did in https://github.com/foostan/kbd/pull/8). This will require to convert to KiCad 6 first.

What is the plan for integrating [`kicad6_crkbd4`](https://github.com/foostan/kbd/tree/kicad6_crkbd4) into `master`?
